# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the BUGFIX-36 branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: abinmn/gcp-storage-bucket-action@v1.0
        with:
    # GCP service key encoded as base64. The account associated with the key should have permissions to make changes in storage bucket.
          service_key:  ${{secrets.gcp_servicekey}}
    # Bucket name
          bucket_name: ${{secrets.gcp_bucketname}}
    # Name of the project that contains the storage bucket.
          project: ${{secrets.gcp_projectpath}}
    # Path of your homepage in cloud storage bucket.
          home_page_path: "/index.html"
    # Path of the 404 page to be shown
          error_page_path: "/404.html"
          build_folder: ${{ github.workspace }} 
